### ISSUE TITLE
How do I know what to add to this repo

### ISSUE THREAD

**Issue by maulanaakbardj** [maulanaakbardj/freecodes_2022#16]
**Please note** In order to have a successful contribution and get your pull request accepted, please follow each and every step given in [Contributing.md](https://github.com/maulanaakbardj/freecodes_Hacktoberfest2022/blob/main/Contributing.md) very precisely.

**Comment by alpesh-rama** [comment]
Please assign me to this issue. Thank you

**Comment by alpesh-rama** [comment]
Hello @maulanaakbardj, please see my related PR. Hopefully this is what you had in mind. If anything additional is required - please let me know. Thank you! Alps.

**Comment by maulanaakbardj** [comment]
Thanks, @alpesh-rama !!

**Comment by harshiitsingh** [comment]
Hey @maulanaakbardj, please assign this issue to me.

**Comment by Klaywert** [comment]
hi, can you please assign me to this issue? Thank you!
